apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: vipinpkddocker/nodejs-project
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: mongodb://db:27017/todos
